services:
  - name: default
    type: web
    runtime: image
    image:
      url: docker.io/mathesar/mathesar:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "8000"
