services:
  - name: default
    type: web
    runtime: image
    image:
      url: docker.io/dgtlmoon/changedetection.io:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "5000"
    disk:
      name: default-datastore
      mountPath: /datastore
      sizeGB: 10
