services:
  - name: default
    type: web
    runtime: image
    image:
      url: docker.io/rook1e404/fusion:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PASSWORD
        value: rss123456
      - key: PORT
        value: "8080"
    disk:
      name: default-data
      mountPath: /data
      sizeGB: 10
