global:
  nameOverride: ""
  fullnameOverride: ""
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
services:
  default:
    enabled: true
    replicaCount: 1
    image:
      repository: docker.io/getmeili/meilisearch
      pullPolicy: IfNotPresent
      tag: latest
    service:
      type: ClusterIP
      ports:
        - port: 7700
          targetPort: 7700
          protocol: TCP
    environment:
      regular: {}
      sensitive: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: default-meili-data
        mountPath: /meili_data
        hostPath: $(pwd)/meili_data
dependencies: {}
