services:
  - name: default
    type: web
    runtime: image
    image:
      url: docker.io/nocodb/nocodb:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
    disk:
      name: default-usr-app-data-
      mountPath: /usr/app/data/
      sizeGB: 10
