global:
  nameOverride: ""
  fullnameOverride: ""
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
services:
  default:
    enabled: true
    replicaCount: 1
    image:
      repository: docker.io/n8nio/n8n
      pullPolicy: IfNotPresent
      tag: latest
    service:
      type: ClusterIP
      ports:
        - port: 5678
          targetPort: 5678
          protocol: TCP
    environment:
      regular: {}
      sensitive: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: default-home-node-n8n
        mountPath: /home/node/.n8n
        hostPath: n8n_data
dependencies: {}
