global:
  nameOverride: ""
  fullnameOverride: ""
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
services:
  default:
    enabled: true
    replicaCount: 1
    image:
      repository: docker.io/erudikaltd/scoold
      pullPolicy: IfNotPresent
      tag: latest_stable
    service:
      type: ClusterIP
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    environment:
      regular:
        JAVA_OPTS: -Dconfig.file=/scoold/application.conf
      sensitive: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: default-scoold-application-conf
        mountPath: /scoold/application.conf
        hostPath: ./scoold-application.conf
dependencies: {}
