services:
  - name: default
    type: web
    runtime: image
    image:
      url: ghcr.io/explodingcamera/liwan:1.1
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "9042"
    disk:
      name: default-data
      mountPath: /data
      sizeGB: 10
